name: chopper_example
description: Example usage of the Chopper package
version: 0.0.3
documentation: https://hadrien-lejard.gitbook.io/chopper/
#author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  chopper:
  json_annotation:
  built_value:
  analyzer:
  http:
  built_collection:
  squadron: ^4.3.0

dev_dependencies:
  build_runner:
  chopper_generator:
  json_serializable:
  built_value_generator:
  dart_code_metrics: ^4.8.1
  lints: ^2.0.0
  squadron_builder: ^0.9.0

dependency_overrides:
 chopper:
   path: ../chopper
 chopper_generator:
   path: ../chopper_generator
