name: chopper_example
description: Example usage of the Chopper package
version: 0.0.6
documentation: https://hadrien-lejard.gitbook.io/chopper/
#author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: ^3.0.0

dependencies:
  chopper:
  json_annotation: ^4.9.0
  built_value:
  analyzer: ^6.4.1
  http: ^1.1.0
  built_collection: ^5.1.1
  squadron: ^5.1.6

dev_dependencies:
  build_runner: ^2.4.9
  chopper_generator:
  json_serializable: ^6.8.0
  built_value_generator: ^8.9.2
  lints: ^4.0.0
  squadron_builder: ^2.4.5

dependency_overrides:
 chopper:
   path: ../chopper
 chopper_generator:
   path: ../chopper_generator
