name: chopper_example
description: Example usage of the Chopper package
version: 0.0.1
documentation: https://hadrien-lejard.gitbook.io/chopper/
#author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#  angular: ^6.0.1
  chopper:
  json_annotation:
  built_value:
  analyzer:

dev_dependencies:
  build_runner:
  chopper_generator:
#  build_web_compilers: ^2.0.0
  json_serializable:
  built_value_generator:

dependency_overrides:
 chopper:
   path: ../chopper
 chopper_generator:
   path: ../chopper_generator
# analyzer: ^3.0.0
