# Created with https://github.com/dart-lang/mono_repo
language: dart

# Custom configuration
sudo: required
addons:
  chrome: stable

install:
  - gem install coveralls-lcov

jobs:
  include:
    - stage: analyze_format_test
      name: "SDK: stable - chopper"
      script: ./tool/travis.sh dartanalyzer dartfmt test
      env: PKG="chopper"
      dart: stable
    - stage: analyze_format_test
      name: "SDK: stable - chopper generator"
      script: ./tool/travis.sh dartanalyzer dartfmt test
      env: PKG="chopper_generator"
      dart: stable
    - stage: analyze_format_test
      name: "SDK: stable - example"
      script: ./tool/travis.sh dartanalyzer dartfmt test
      env: PKG="example"
      dart: stable

stages:
  - analyze_format_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - chopper/.dart_tool
    - chopper_generator/.dart_tool
    - example/.dart_tool