name: chopper_generator
description: Chopper is an http client generator using source_gen, inspired by Retrofit
version: 5.0.0
documentation: https://hadrien-lejard.gitbook.io/chopper
repository: https://github.com/lejard-h/chopper

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^4.1.0
  build: ^2.0.0
  built_collection: ^5.0.0
  chopper: ^5.0.0
  code_builder: ^4.1.0
  dart_style: ^2.0.0
  logging: ^1.0.0
  meta: ^1.3.0
  source_gen: ^1.0.0

dev_dependencies:
  test: ^1.16.4
  dart_code_metrics: ^4.8.1
  lints: ^2.0.0

dependency_overrides:
  # Comment before publish
  chopper:
    path: ../chopper
