name: chopper_generator
description: Chopper is an http client generator using source_gen, inspired by Retrofit
version: 8.0.1
documentation: https://hadrien-lejard.gitbook.io/chopper
repository: https://github.com/lejard-h/chopper

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  built_collection: ^5.1.1
  chopper: ^8.0.1
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  logging: ^1.2.0
  meta: ^1.9.1
  source_gen: ^1.5.0
  yaml: ^3.1.2
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.25.5

dependency_overrides:
  chopper:
    path: ../chopper

topics:
  - api
  - codegen
  - http
  - rest
