name: chopper_generator
description: Chopper is an http client generator using source_gen and inspired from retrofit
version: 3.0.6
homepage: https://hadrien-lejard.gitbook.io/chopper
repository: https://github.com/lejard-h/chopper
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  meta: ^1.2.3
  analyzer: ^0.40.4
  build: ^1.5.0
  logging: ^0.11.4
  source_gen: ^0.9.7+1
  chopper: ^3.0.3
  code_builder: ^3.5.0
  dart_style: ^1.3.7
  built_collection: ^4.3.2

dev_dependencies:
  test: ^1.15.4
  pedantic: ^1.9.2

# Uncomment for development
# dependency_overrides:
#   chopper:
#     path: ../chopper
