name: chopper_generator
description: Chopper is an http client generator using source_gen, inspired by Retrofit
version: 8.4.0
documentation: https://hadrien-lejard.gitbook.io/chopper
repository: https://github.com/lejard-h/chopper

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ">=8.0.0 <10.0.0"
  build: ^4.0.3
  built_collection: ^5.1.1
  chopper: ^8.4.0
  code_builder: ^4.11.0
  logging: ^1.3.0
  meta: ^1.17.0
  source_gen: ^4.1.1
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.10.4
  build_verify: ^3.1.1
  http: ^1.6.0
  lints: ^6.0.0
  test: ^1.28.0

topics:
  - api
  - codegen
  - http
  - rest
