name: chopper_generator
description: Chopper is an http client generator using source_gen, inspired by Retrofit
version: 4.0.1
documentation: https://hadrien-lejard.gitbook.io/chopper
repository: https://github.com/lejard-h/chopper
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^2.0.0
  build: ^2.0.0
  built_collection: ^5.0.0
  chopper: ^4.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.0
  logging: ^1.0.0
  meta: ^1.3.0
  source_gen: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.15.4

dependency_overrides:
  # Comment before publish
  chopper:
    path: ../chopper
