name: chopper_generator
description: Chopper is an http client generator using source_gen, inspired by Retrofit
version: 7.0.0
documentation: https://hadrien-lejard.gitbook.io/chopper
repository: https://github.com/lejard-h/chopper

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=5.13.0 <7.0.0"
  build: ^2.4.1
  built_collection: ^5.1.1
  chopper: ^7.0.0
  code_builder: ^4.5.0
  dart_style: ^2.3.2
  logging: ^1.2.0
  meta: ^1.9.1
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  http: ^1.1.0
  lints: ^2.1.1
  test: ^1.24.4

dependency_overrides:
  # Comment before publish
  chopper:
    path: ../chopper
