name: chopper_generator
description: Chopper is an http client generator using source_gen, inspired by Retrofit
version: 4.0.0
documentation: https://hadrien-lejard.gitbook.io/chopper
repository: https://github.com/lejard-h/chopper
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.2.3
  analyzer: ^1.1.0
  build: ^1.6.3
  logging: ^1.0.0
  source_gen: ^0.9.10+3
  chopper: ^4.0.0
  code_builder: ^3.6.0
  dart_style: ^1.3.14
  built_collection: ^5.0.0

dev_dependencies:
  test: ^1.15.4
  pedantic: ^1.9.2

# Uncomment for development
dependency_overrides:
  chopper:
    path: ../chopper
