name: chopper_generator
description: Chopper is an http client generator using source_gen and inspired from retrofit
version: 2.5.0
homepage: https://github.com/lejard-h/chopper
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  meta: ^1.1.2
  analyzer: '>=0.35.0 <1.0.0'
  build: ^1.0.0
  logging: ^0.11.0
  source_gen: ^0.9.0
  chopper: ^2.5.0
  code_builder: ^3.0.0
  dart_style: ^1.0.10
  built_collection: ^4.0.0

dev_dependencies:
  test: ^1.3.0

dependency_overrides:
  chopper:
    path: ../chopper
