name: chopper_generator
description: Chopper is an http client generator using source_gen and inspired from retrofit
version: 3.0.5
homepage: https://hadrien-lejard.gitbook.io/chopper
repository: https://github.com/lejard-h/chopper
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  meta: ^1.1.8
  analyzer: ^0.39.8
  build: ^1.3.0
  logging: ^0.11.4
  source_gen: ^0.9.5
  chopper: ^3.0.2
  code_builder: ^3.2.1
  dart_style: ^1.3.6
  built_collection: ^4.3.2

dev_dependencies:
  test: ^1.14.3
  pedantic: ^1.9.0

dependency_overrides:
  chopper:
    path: ../chopper
