name: chopper
description: Chopper is an http client generator using source_gen, inspired by Retrofit
version: 6.1.4
documentation: https://hadrien-lejard.gitbook.io/chopper
repository: https://github.com/lejard-h/chopper

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  http: ">=0.13.0 <2.0.0"
  logging: ^1.0.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  collection: ^1.16.0
  coverage: ^1.0.2
  dart_code_metrics: '>=4.8.1 <6.0.0'
  data_fixture_dart: ^2.2.0
  faker: ^2.1.0
  http_parser: ^4.0.0
  lints: ^2.0.0
  test: ^1.16.4
  transparent_image: ^2.0.0
  chopper_generator:
    path: ../chopper_generator
