name: chopper
description: Chopper is an http client generator using source_gen and inspired from retrofit
version: 3.0.3
homepage: https://hadrien-lejard.gitbook.io/chopper
repository: https://github.com/lejard-h/chopper
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ">=0.11.0 <1.0.0"
  meta: ^1.1.8
  logging: ^0.11.4

dev_dependencies:
  test: ^1.14.3
  build_runner: ^1.10.0
  build_test: ^1.0.0
  coverage: ^0.13.9
  test_coverage: ^0.4.1
  http_parser: ^3.1.4
  pedantic: ^1.9.0
  chopper_generator:
    path: ../chopper_generator
