name: chopper_built_value
description: A built_value based Converter for Chopper.
version: 1.2.2
documentation: https://hadrien-lejard.gitbook.io/chopper/converters/built-value-converter
repository: https://github.com/lejard-h/chopper

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  built_value: ^8.0.0
  built_collection: ^5.0.0
  chopper: ^6.0.0
  http: ">=0.13.0 <2.0.0"

dev_dependencies:
  test: ^1.16.4
  build_runner: ^2.0.0
  build_test: ^2.0.0
  built_value_generator: ^8.0.6
  dart_code_metrics: '>=4.8.1 <6.0.0'
  lints: ^2.0.0

dependency_overrides:
  # Comment before publish
  chopper:
    path: ../chopper
