name: chopper_built_value
description: A built_value based Converter for Chopper.
version: 3.2.0
documentation: https://hadrien-lejard.gitbook.io/chopper/converters/built-value-converter
repository: https://github.com/lejard-h/chopper

environment:
  sdk: ^3.9.0

dependencies:
  built_value: ^8.12.1
  built_collection: ^5.1.1
  chopper: ^8.4.0
  http: ^1.6.0

dev_dependencies:
  test: ^1.28.0
  build_runner: ^2.10.4
  build_test: ^3.5.4
  built_value_generator: ^8.12.1
  lints: ^6.0.0

topics:
  - codegen
  - converter
  - built-value
