name: chopper_built_value
description: A built_value based Converter for Chopper.
version: 1.0.0
documentation: https://hadrien-lejard.gitbook.io/chopper/converters/built-value-converter
repository: https://github.com/lejard-h/chopper
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  built_value: ^8.0.0
  built_collection: ^5.0.0
  chopper: ^4.0.0
  http: ^0.13.0

dev_dependencies:
  test: ^1.16.4
  build_runner: ^2.0.0
  build_test: ^2.0.0
  built_value_generator: ^8.0.6
  pedantic: ^1.10.0

dependency_overrides:
  # Comment before publish
  chopper:
    path: ../chopper
